import 'package:build/build.dart';
import 'package:flutter_graphql_codegen/flutter_graphql_codegen.dart';
import 'package:test/test.dart';

void main() {
  group('Code Generation Tests', () {
    test('Generated types file should contain warning comment', () {
      final simpleSchema = '''
        type Query {
          hello: String
        }
        
        type User {
          id: ID!
          name: String!
        }
      ''';

      final generatedCode =
          GraphQLCodeGenerator.generateTypesFile(simpleSchema);

      expect(
          generatedCode,
          startsWith(
              '// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED MANUALLY'));
      expect(
          generatedCode,
          contains(
              '// Any manual changes will be overwritten during code generation'));
      expect(
          generatedCode, contains('// Generated by flutter_graphql_codegen'));
    });

    test('Generated operation file should contain warning comment', () {
      final simpleSchema = '''
        type Query {
          hello: String
        }
      ''';

      final documentContent = '''
        query GetHello {
          hello
        }
      ''';

      final typesContent = 'class User {}';

      final generatedCode = GraphQLCodeGenerator.generateOperationFile(
        simpleSchema,
        documentContent,
        'GetHello',
        'Query',
        typesContent,
      );

      expect(
          generatedCode,
          startsWith(
              '// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED MANUALLY'));
      expect(
          generatedCode,
          contains(
              '// Any manual changes will be overwritten during code generation'));
      expect(
          generatedCode, contains('// Generated by flutter_graphql_codegen'));
    });
  });

  group('Legacy Tests', () {
    final awesome = Awesome();

    setUp(() {
      // Additional setup goes here.
    });

    test('First Test', () {
      expect(awesome.isAwesome, isTrue);
      final builderOptions = BuilderOptions({
        'config_path': 'test/fixtures/graphql_codegen.yaml',
      });
      graphqlCodegenBuilder(builderOptions);
      /* builder.build(BuildStep()); */
    });
  });
}
