builders:
  graphql_codegen:
    import: "package:flutter_graphql_codegen/flutter_graphql_codegen.dart"
    builder_factories: ["GraphQLCodegenBuilder"]
    build_extensions: {".dart": [".graphql.dart"]}
    auto_apply: root_package
    build_to: source