name: flutter_graphql_codegen
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/ifmelate/flutter_graphql_codegen.git

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  path: ^1.8.1
  build: ^2.0.0
  yaml: ^3.1.0
  http: ^1.1.2
  graphql: ^5.1.3
  glob: ^2.1.0
  gql: ^1.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^4.0.0
  build_runner: ^2.4.6
  test: ^1.24.0
  json_serializable: ^6.7.1
