name: flutter_graphql_codegen
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  build: ^2.0.0
  yaml: ^3.1.0
  http: ^1.1.2
  graphql: ^5.0.0
  glob: ^2.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
