import 'dart:async';
import 'dart:io';

import 'package:build/build.dart';
import 'package:gql/language.dart' as gql_lang;
import 'package:flutter_graphql_codegen/src/schema_downloader.dart';
import 'package:flutter_graphql_codegen/src/utils.dart';
import 'package:flutter_graphql_codegen/src/type_generator.dart';
import 'package:flutter_graphql_codegen/src/client_extension_generator.dart';
import 'package:flutter_graphql_codegen/src/operation_analyzer.dart';
import 'package:path/path.dart' as p;

import 'config.dart';

class GraphQLCodegenBuilder implements Builder {
  final GraphQLCodegenConfig config;
  static bool _typesFileGenerated = false;

  GraphQLCodegenBuilder(this.config);

  @override
  FutureOr<void> build(BuildStep buildStep) async {
    final inputId = buildStep.inputId;

    // Skip non-GraphQL files
    if (!inputId.path.endsWith('.graphql')) {
      return;
    }

    // Skip schema files
    if (inputId.path.contains('schema.graphql')) {
      return;
    }

    print('🔧 Processing GraphQL operation: ${inputId.path}');

    // Load schema (supports http/https, file:// and local paths)
    final schema = await SchemaDownloader.downloadSchema(config.schemaUrl);

    // Read GraphQL document content
    final content = await buildStep.readAsString(inputId);

    // Extract operation name and type from document
    final operationName = _extractOperationName(content);
    final operationType = _extractOperationType(content);

    if (operationName != null && operationType != null) {
      print('📝 Generating code for: $operationName ($operationType)');

      // Generate client extension for this specific operation
      final schemaDoc = gql_lang.parseString(schema);
      final typesCode = TypeGenerator.generateTypesFile(schema);

      // Generate types.dart file only once
      if (!_typesFileGenerated) {
        await _generateTypesFileIfNeeded(typesCode);
        _typesFileGenerated = true;
      }

      final definedTypes = OperationAnalyzer.extractDefinedTypes(typesCode);
      final clientExtension = ClientExtensionGenerator.generateClientExtension(
        operationName,
        operationType,
        content,
        schemaDoc,
        definedTypes,
      );

      // Create operation file content
      final operationFileCode = '''// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by flutter_graphql_codegen
// Operation: $operationName ($operationType)

import 'package:graphql/client.dart' as graphql;
import 'types.dart';

$clientExtension
''';

      // Generate files directly in output directory specified in config
      await _writeToOutputDirectory(operationName, operationFileCode);

      print(
          '📝 Generated: ${config.outputDir}/${_generateOutputFileName(operationName)}');
    }

    // Generate index file after processing all operations
    await _generateIndexFile();
  }

  /// Generates index.dart file with all operations
  Future<void> _generateIndexFile() async {
    try {
      // Find all generated .g.dart files
      final generatedFiles = <File>[];
      await _findGeneratedFiles(generatedFiles);

      final exports = <String>[];
      final operations = <String>[];

      for (final file in generatedFiles) {
        final content = await file.readAsString();

        if (!content.contains('Generated by flutter_graphql_codegen')) {
          continue;
        }

        // Files are in the same folder as index.dart, use a safe file name
        final fileName = p.basename(file.path);
        exports.add("export '$fileName';");

        // Extract operation name from file name (snake_case_graphql.g.dart -> SnakeCaseGraphql)
        final operationName = fileName
            .replaceAll('_graphql.g.dart', '')
            .split('_')
            .map((word) => word[0].toUpperCase() + word.substring(1))
            .join('');
        operations.add('// $operationName');
      }

      if (exports.isEmpty) {
        print('📁 No generated GraphQL files found for index');
        return;
      }

      // Create index file
      final indexContent = '''// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by flutter_graphql_codegen
// GraphQL operations index

// Export types
export 'types.dart';

// Export all generated operations
${exports.join('\n')}

// Available operations:
${operations.join('\n')}

// Usage:
// import 'package:your_app/${config.outputDir}/index.dart';
// 
// final client = GraphQLClient(...);
// final result = await client.getUserProfile({'culture': 'en'});
''';

      // Create the directory if it does not exist
      final outputDir = Directory(config.outputDir);
      if (!outputDir.existsSync()) {
        await outputDir.create(recursive: true);
      }

      // Write index file
      final indexFile = File('${config.outputDir}/index.dart');
      await indexFile.writeAsString(indexContent);

      print('📝 Generated index file: ${indexFile.path}');
      print('✅ Index complete! Found ${exports.length} operations');
    } catch (e) {
      print('⚠️ Error generating index file: $e');
    }
  }

  /// Generates types.dart file
  Future<void> _generateTypesFileIfNeeded(String typesCode) async {
    // Create the directory if it does not exist
    final outputDir = Directory(config.outputDir);
    if (!outputDir.existsSync()) {
      await outputDir.create(recursive: true);
    }

    // Always generate the types.dart file
    final typesFile = File(p.join(config.outputDir, 'types.dart'));
    await typesFile.writeAsString(typesCode);
    print('📝 Generated types file: ${typesFile.path}');
  }

  /// Writes operation file to the configured output directory
  Future<void> _writeToOutputDirectory(
      String operationName, String content) async {
    // Create the directory if it does not exist
    final outputDir = Directory(config.outputDir);
    if (!outputDir.existsSync()) {
      await outputDir.create(recursive: true);
    }

    // Create the file in the output directory
    final fileName = _generateOutputFileName(operationName);
    final filePath = p.join(config.outputDir, fileName);
    final file = File(filePath);

    await file.writeAsString(content);
  }

  /// Finds all generated .g.dart files
  Future<void> _findGeneratedFiles(List<File> files) async {
    // Search files in the output directory instead of the entire lib
    final outputDir = Directory(config.outputDir);
    if (!outputDir.existsSync()) {
      return;
    }

    await for (final entity
        in outputDir.list(recursive: true, followLinks: false)) {
      if (entity is File && entity.path.endsWith('.g.dart')) {
        files.add(entity);
      }
    }
  }

  /// Extracts operation name from GraphQL document content
  String? _extractOperationName(String content) {
    final operations = parseOperations(content);
    return operations.isNotEmpty ? operations.first.name : null;
  }

  /// Extracts operation type from GraphQL document content
  String? _extractOperationType(String content) {
    final operations = parseOperations(content);
    return operations.isNotEmpty ? operations.first.type : null;
  }

  /// Generates the output file name based on operation name
  /// Example: GetDrugList -> get_drug_list_graphql.g.dart
  String _generateOutputFileName(String operationName) {
    final snakeCaseName = _camelToSnakeCase(operationName);
    return '${snakeCaseName}_graphql.g.dart';
  }

  /// Converts camelCase to snake_case
  /// Example: GetDrugList -> get_drug_list, ContinueVisit -> continue_visit
  String _camelToSnakeCase(String input) {
    return input
        .replaceAllMapped(RegExp(r'(?<!^)(?=[A-Z])'), (match) => '_')
        .toLowerCase();
  }

  @override
  Map<String, List<String>> get buildExtensions => {
        '.graphql': ['.g.dart'],
      };
}

Builder graphqlCodegenBuilder(BuilderOptions options) {
  final configPath = options.config['config_path'] as String?;
  if (configPath == null) {
    throw ArgumentError('Missing config_path in builder options');
  }

  final configFile = File(configPath);
  if (!configFile.existsSync()) {
    throw FileSystemException('Config file not found', configPath);
  }

  final yamlString = configFile.readAsStringSync();

  try {
    final config = GraphQLCodegenConfig.fromYaml(yamlString);
    return GraphQLCodegenBuilder(config);
  } catch (e, stackTrace) {
    print('Error parsing config: $e');
    print('Stack trace: $stackTrace');
    rethrow;
  }
}
