/// Utility classes and extensions for code generation
library;

import 'package:gql/ast.dart';

/// Constants for code generation
class CodeGenerationConstants {
  /// Warning header for generated files
  static const String generatedFileWarning =
      '''// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED MANUALLY
// Any manual changes will be overwritten during code generation
// Generated by flutter_graphql_codegen''';
}

/// Extension methods for string manipulation
extension StringExtension on String {
  /// Capitalizes the first letter of the string
  String capitalize() {
    if (isEmpty) return this;
    return "${this[0].toUpperCase()}${substring(1)}";
  }

  /// Converts string to camelCase
  String toCamelCase() {
    if (length < 2) {
      return toLowerCase();
    }
    return "${this[0].toLowerCase()}${substring(1)}";
  }
}

/// Extension for TypeNode to check if it's non-null
extension TypeNodeExtensions on TypeNode {
  /// True if this node is marked non-null in the GraphQL AST
  bool get isNonNull {
    if (this is NamedTypeNode) {
      return (this as NamedTypeNode).isNonNull;
    }
    if (this is ListTypeNode) {
      return (this as ListTypeNode).isNonNull;
    }
    return false;
  }
}

/// Constants for GraphQL scalar types
class GraphQLConstants {
  static const Set<String> builtInScalars = {
    'Int',
    'Float',
    'String',
    'Boolean',
    'ID',
    'Short'
  };

  static const Map<String, String> scalarToDartType = {
    'Int': 'int',
    'Float': 'double',
    'String': 'String',
    'Boolean': 'bool',
    'ID': 'String',
    'Short': 'int',
    'DateTime': 'DateTime',
    'LocalDate': 'DateTime',
  };
}

/// Global state for tracking custom types and enums
class TypeRegistry {
  static final Set<String> _customScalars = <String>{};
  static final Set<String> _enumTypes = <String>{};
  static final Set<String> _objectTypes = <String>{};

  static Set<String> get customScalars => _customScalars;
  static Set<String> get enumTypes => _enumTypes;
  static Set<String> get objectTypes => _objectTypes;

  static void clear() {
    _customScalars.clear();
    _enumTypes.clear();
    _objectTypes.clear();
  }

  static void addCustomScalar(String scalar) {
    _customScalars.add(scalar);
  }

  static void addEnumType(String enumType) {
    _enumTypes.add(enumType);
  }

  static void addObjectType(String typeName) {
    _objectTypes.add(typeName);
  }

  static bool isEnum(String typeName) {
    return _enumTypes.contains(typeName);
  }

  static bool isCustomScalar(String typeName) {
    return _customScalars.contains(typeName);
  }
}
